### ISSUE TITLE
ck.py should support CFLX flag

### ISSUE THREAD

**Issue by zhi-wang** [roseane-reis/tinker9#1]
Please remind me to add this support to ck.py (v2). We'll then spend some time to update (v1.5) hippo kernels with v2 script.

**Comment by zhi-wang** [comment]
Hi, please take a look at this commit https://github.com/TinkerTools/tinker9/commit/aafd45d40ef41294d2e727dac0b8d40674afd558 under the hippo branch. I changed both "ck.py" and "epolar_chgpen_cu1.yaml" files.

If you click on this link, you'll see I started using AT_AT syntax in the yaml file, and the CFLX flag was supported by an extra `onlyif: CFLX` tag in the `def` entry. I don't really want to change the hippo epolar cuda file tonight because I am tired of big commits recently :(

I will rely on you to compile and test the automated CFLX-enabled kernels for epolar and empole. You'll also need to update the yaml file for hippo empole of course. If you are happy about this change, you can go ahead and close this issue.

Thanks!

**Comment by roseane-reis** [comment]
I have updated the kernels that use CFLX. It works well.
